apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo-traces
    type: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: webstore-logs
        spanStartTimeShift: "-20m"
        spanEndTimeShift: "20m"
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: traceId:"$${__trace.traceId}" AND spanId:"$${__span.spanId}"
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus
